module.exports = {
  language: 'en',
   BASE_URL: 'http://3.17.73.124/boomoversea/public/api/',
  Signin :'Signin',
  Signup :'Signup',
  front_main :'front_main',
  user_id :'12',
  industry :'',
  category : '',
  derive_detail_industry :'derive_detail_industry',
  derive_detail_category : 'derive_detail_category',
  info_number :'',
  info_email : '',
  job_id :'',
  profile :'',
  subjectId : '',
  industry_id :'',
  update_user_information :'update_user_information',
  gallery :'',
  industryName :'',
  globalCountryList :[],
  news :[],
  countries :'countries',
  gender :'',
  videoLink :'',
  subject : '',
  mainid : '',
  userID :'',
  dervie_detail_of_product : 'dervie_detail_of_product',
  key :'AIzaSyCBfpNuQHBQOC7sX8wzOX-C_izlwzEbjNQ',
  token :'67mVMWSZ46pd6ZVJ2IBtTS7U9udsm3sh8XSYTUG0QaBP0eX1BLNtjUT17B9u',
accessToken :'',
  need_help:'need_help',
  COLOR: {
    ORANGE: '#C50',
    DARKBLUE: '#0F3274',
    LIGHTBLUE: '#6EA8DA',
    DARKGRAY: '#999',
  },
};
